// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1gzqNZBq2ez1cCZd-ajVuk7_kfezh_TE',
    appId: '1:712042451427:web:fc050b82fd874e3364d0d6',
    messagingSenderId: '712042451427',
    projectId: 'earlywarningsystem-53511',
    authDomain: 'earlywarningsystem-53511.firebaseapp.com',
    databaseURL: 'https://earlywarningsystem-53511-default-rtdb.firebaseio.com',
    storageBucket: 'earlywarningsystem-53511.firebasestorage.app',
    measurementId: 'G-7L8E988Q4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC93BuLJSF6_eYR1_DwJjSayyWPP1zVMmQ',
    appId: '1:712042451427:android:c305711e36d0568764d0d6',
    messagingSenderId: '712042451427',
    projectId: 'earlywarningsystem-53511',
    databaseURL: 'https://earlywarningsystem-53511-default-rtdb.firebaseio.com',
    storageBucket: 'earlywarningsystem-53511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-tOtJCjRAF9XnQgddMRmTkTqzV5LCBAw',
    appId: '1:712042451427:ios:999c97667f7ba81c64d0d6',
    messagingSenderId: '712042451427',
    projectId: 'earlywarningsystem-53511',
    databaseURL: 'https://earlywarningsystem-53511-default-rtdb.firebaseio.com',
    storageBucket: 'earlywarningsystem-53511.firebasestorage.app',
    iosBundleId: 'com.earlywarning.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-tOtJCjRAF9XnQgddMRmTkTqzV5LCBAw',
    appId: '1:712042451427:ios:a26330234ca953f864d0d6',
    messagingSenderId: '712042451427',
    projectId: 'earlywarningsystem-53511',
    databaseURL: 'https://earlywarningsystem-53511-default-rtdb.firebaseio.com',
    storageBucket: 'earlywarningsystem-53511.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1gzqNZBq2ez1cCZd-ajVuk7_kfezh_TE',
    appId: '1:712042451427:web:237a301775f7171c64d0d6',
    messagingSenderId: '712042451427',
    projectId: 'earlywarningsystem-53511',
    authDomain: 'earlywarningsystem-53511.firebaseapp.com',
    databaseURL: 'https://earlywarningsystem-53511-default-rtdb.firebaseio.com',
    storageBucket: 'earlywarningsystem-53511.firebasestorage.app',
    measurementId: 'G-R8KMJJZC03',
  );
}
